// src/react/root.ts
import type { ReactNode } from 'react'
import { SmithersReconciler } from './renderer.js'
import type { SmithersNode } from '../core/types.js'
import { serialize } from '../core/serialize.js'
import { createOrchestrationPromise } from '../components/Ralph.jsx'

// Type for the fiber root container
type FiberRoot = ReturnType<typeof SmithersReconciler.createContainer>

/**
 * Smithers root for mounting React components.
 */
export interface SmithersRoot {
  /**
   * Mount the app and wait for orchestration to complete.
   * Returns a Promise that resolves when Ralph signals completion.
   */
  mount(App: () => ReactNode | Promise<ReactNode>): Promise<void>
  getTree(): SmithersNode
  dispose(): void
  /**
   * Serialize the tree to XML for display/approval.
   * This is crucial for showing users the agent plan before execution.
   */
  toXML(): string
}

/**
 * Create a Smithers root for rendering React components to SmithersNode trees.
 */
export function createSmithersRoot(): SmithersRoot {
  const rootNode: SmithersNode = {
    type: 'ROOT',
    props: {},
    children: [],
    parent: null,
  }

  let fiberRoot: FiberRoot | null = null

  return {
    async mount(App: () => ReactNode | Promise<ReactNode>): Promise<void> {
      // Clean up previous render
      if (fiberRoot) {
        SmithersReconciler.updateContainer(null, fiberRoot, null, () => {})
        rootNode.children = []
      }

      // Create a promise that Ralph will resolve when orchestration completes
      const completionPromise = createOrchestrationPromise()

      // Check if App returns a Promise
      const result = App()

      let element: ReactNode

      if (result && typeof (result as any).then === 'function') {
        // App is async - we need to await the JSX first
        element = await (result as Promise<ReactNode>)
      } else {
        // App is sync
        element = result
      }

      // Create the fiber root container
      // createContainer signature: (containerInfo, tag, hydrate, hydrationCallbacks, isStrictMode, concurrentUpdatesByDefaultOverride, identifierPrefix, transitionCallbacks)
      fiberRoot = SmithersReconciler.createContainer(
        rootNode, // container
        0, // LegacyRoot tag (ConcurrentRoot = 1)
        null, // hydrationCallbacks
        false, // isStrictMode
        null, // concurrentUpdatesByDefaultOverride
        '', // identifierPrefix
        (error: Error) => console.error('Smithers recoverable error:', error), // onRecoverableError
        null // transitionCallbacks
      )

      // Render the app
      SmithersReconciler.updateContainer(element, fiberRoot, null, () => {})

      // Flush the initial render synchronously
      SmithersReconciler.flushSync(() => {})

      // Wait for orchestration to complete (Ralph will signal this)
      await completionPromise
    },

    getTree(): SmithersNode {
      return rootNode
    },

    dispose(): void {
      if (fiberRoot) {
        SmithersReconciler.updateContainer(null, fiberRoot, null, () => {})
        fiberRoot = null
      }
      rootNode.children = []
    },

    toXML(): string {
      return serialize(rootNode)
    },
  }
}

// src/solid/root.ts
import type { JSX } from 'solid-js'
import { render } from './renderer.js'
import type { SmithersNode } from '../core/types.js'
import { serialize } from '../core/serialize.js'
import { createOrchestrationPromise } from '../components/Ralph.jsx'

/**
 * Smithers root for mounting Solid components.
 */
export interface SmithersRoot {
  /**
   * Mount the app and wait for orchestration to complete.
   * Returns a Promise that resolves when Ralph signals completion.
   */
  mount(App: () => JSX.Element | Promise<JSX.Element>): Promise<void>
  getTree(): SmithersNode
  dispose(): void
  /**
   * Serialize the tree to XML for display/approval.
   * This is crucial for showing users the agent plan before execution.
   */
  toXML(): string
}

/**
 * Create a Smithers root for rendering Solid components to SmithersNode trees.
 */
export function createSmithersRoot(): SmithersRoot {
  const rootNode: SmithersNode = {
    type: 'ROOT',
    props: {},
    children: [],
    parent: null,
  }

  let disposeFunction: (() => void) | null = null

  return {
    async mount(App: () => JSX.Element | Promise<JSX.Element>): Promise<void> {
      if (disposeFunction) {
        disposeFunction()
        rootNode.children = []
      }

      // Create a promise that Ralph will resolve when orchestration completes
      const completionPromise = createOrchestrationPromise()

      // Handle async App functions by awaiting them first
      const result = App()
      let element: JSX.Element

      if (result && typeof (result as any).then === 'function') {
        // App is async - await the promise to get the JSX
        element = await (result as Promise<JSX.Element>)
      } else {
        element = result as JSX.Element
      }

      // Wrap in a sync function for the renderer
      const AppWrapper = () => element

      // The renderer handles JSX.Element → SmithersNode conversion internally
      disposeFunction = render(AppWrapper as any, rootNode)

      // Wait for orchestration to complete (Ralph will signal this)
      await completionPromise
    },

    getTree(): SmithersNode {
      return rootNode
    },

    dispose(): void {
      if (disposeFunction) {
        disposeFunction()
        disposeFunction = null
      }
      rootNode.children = []
    },

    toXML(): string {
      return serialize(rootNode)
    },
  }
}
